version: 2
exclude_patterns:
  - .nyc_output/
  - docs/
  - test/
  - '**/node_modules/'
plugins:
  eslint:
    enabled: true
    channel: 'beta'
checks:
  method-lines:
    enabled: false
  complex-logic:
    enabled: false
  similar-code:
    enabled: false
  method-complexity:
    enabled: false
