version: 2
exclude_patterns:
  - .nyc_output/
  - docs/
  - test/
  - '**/node_modules/'
plugins:
  eslint:
    enabled: true
checks:
  method-lines:
    enabled: false
  complex-logic:
    enabled: false
  similar-code:
    config:
      threshold: 40
  method-complexity:
    enabled: false